### ISSUE TITLE
Impossible to save the wallet

### ISSUE THREAD

**Issue by ikotaki** [cirquity/cirquity-wallet#3]
<!-- 
Hi,

i have just install the windows version of the wallet, but when setting up the wallet , at the last step it is impossible to save the wallet and continue the set up process... And i don't understand why it is impossible to check the balance of my wallet in the blockchain explorer.. Please help me...
--!>

**Comment by deeterd** [comment]
Hello, could you please describe your problem?
May on what system you're using and what version you have?

**Comment by ikotaki** [comment]
Hi,
i am using the version 0.2.3 of the windows wallet, that i can not set up for the first time. After generating new address, secure seed words, at the backup stage it is impossible to save the wallet to Cirquity wallet file... While saving the wallet no file is saved and the wallet qt never start sync or operating...

**Comment by deeterd** [comment]
What version of windows are you using? So I can setup one and test it directly on your version.
I've tried on windows 10 and works perfectly.

Thanks

**Comment by ikotaki** [comment]
i have tested the software on windows 10; windows 8 and windows 7, and having the same issue. May be the release have this issue but not the final one in your repository ???

**Comment by deeterd** [comment]
I have fixed the problem. Please download the new version and give it a try.
https://github.com/cirquity/cirquity-wallet/releases/tag/0.2.4

And don't forget to star the project 💯
