### ISSUE TITLE
impossible to backup old wallet

### ISSUE THREAD

**Issue by ikotaki** [cirquity/cirquity-wallet#4]
Hello,

After reviewing the new release on windows, it show the same error while saving the wallet from seed words recovery.  I pasted the seed words, the software recognize the wallet address but while saving the wallet it doesn't save the wallet file as from the previous issue from 0.2.3

**Comment by ikotaki** [comment]
i also created a new account that is sync but it doesn't show the amount tranfered that is already recorded in the blockchain

**Comment by deeterd** [comment]
Hello, can you try to ReScan your new wallet on height 1076708.
I'm making the new release now for import wallet from seed and keys. Let me know if this release still gives you some errors.

Thanks

**Comment by ikotaki** [comment]
hello, i have tried the last version of the release, and it seems perfect for me... Great job !!! Keep going on !!!
